export enum PRIORITY_LEVELS {
  CRITICA = 1,
  ALTA = 2,
  MEDIA = 3,
  BAJA = 4,
}

export const PRIORITY_NAMES = {
  [PRIORITY_LEVELS.CRITICA]: 'Crítica',
  [PRIORITY_LEVELS.ALTA]: 'Alta',
  [PRIORITY_LEVELS.MEDIA]: 'Media',
  [PRIORITY_LEVELS.BAJA]: 'Baja',
};

export const URGENCY_LEVELS = {
  CRITICA: 1,
  ALTA: 2,
  MEDIA: 3,
  BAJA: 4,
};

export const IMPACT_LEVELS = {
  CRITICO: 1,
  ALTO: 2,
  MEDIO: 3,
  BAJO: 4,
};

// Matriz de prioridad: urgencia x impacto
export const PRIORITY_MATRIX: { [key: string]: number } = {
  '1-1': PRIORITY_LEVELS.CRITICA,
  '1-2': PRIORITY_LEVELS.CRITICA,
  '1-3': PRIORITY_LEVELS.ALTA,
  '1-4': PRIORITY_LEVELS.ALTA,
  '2-1': PRIORITY_LEVELS.CRITICA,
  '2-2': PRIORITY_LEVELS.ALTA,
  '2-3': PRIORITY_LEVELS.ALTA,
  '2-4': PRIORITY_LEVELS.MEDIA,
  '3-1': PRIORITY_LEVELS.ALTA,
  '3-2': PRIORITY_LEVELS.ALTA,
  '3-3': PRIORITY_LEVELS.MEDIA,
  '3-4': PRIORITY_LEVELS.MEDIA,
  '4-1': PRIORITY_LEVELS.ALTA,
  '4-2': PRIORITY_LEVELS.MEDIA,
  '4-3': PRIORITY_LEVELS.MEDIA,
  '4-4': PRIORITY_LEVELS.BAJA,
};