export enum TICKET_STATES {
  NUEVA = 1,
  ASIGNADA = 2,
  EN_PROGRESO = 3,
  ESPERANDO = 4,
  RESUELTA = 5,
  CERRADA = 6,
  CANCELADA = 7,
  REABIERTA = 8,
}

export const STATE_CODES = {
  NUEVA: 'NUEVA',
  ASIGNADA: 'ASIGNADA',
  EN_PROGRESO: 'EN_PROGRESO',
  ESPERANDO: 'ESPERANDO',
  RESUELTA: 'RESUELTA',
  CERRADA: 'CERRADA',
  CANCELADA: 'CANCELADA',
  REABIERTA: 'REABIERTA',
};

export const STATE_NAMES = {
  [TICKET_STATES.NUEVA]: 'Nueva',
  [TICKET_STATES.ASIGNADA]: 'Asignada',
  [TICKET_STATES.EN_PROGRESO]: 'En Progreso',
  [TICKET_STATES.ESPERANDO]: 'Esperando Respuesta',
  [TICKET_STATES.RESUELTA]: 'Resuelta',
  [TICKET_STATES.CERRADA]: 'Cerrada',
  [TICKET_STATES.CANCELADA]: 'Cancelada',
  [TICKET_STATES.REABIERTA]: 'Reabierta',
};

export const FINAL_STATES = [TICKET_STATES.CERRADA, TICKET_STATES.CANCELADA];